### PR TITLE
included Mogi volume change parameter to explosion source

### PR DESCRIPTION
**Pull request by hvasbath**

### CODE REVIEW

**Comment by hvasbath** [comment]
Could someone please review this @miili

**Comment by miili** [comment]
Is this necessary? Could prevent common-stacking for different amplitudes/volumes. @emolch 
```
def base_key(self):
    return Source.base_key(self) + (self.volume_change, )
```

**Comment by hvasbath** [comment]
There is still a stray print ;)

**Comment by emolch** [comment]
I rebased to current master, added two commits and pushed to branch explosion_volume_change in pyrocko/pyrocko. But let's discuss in the hive how to proceeed.

**Comment by miili** [comment]
I advertise for an even more flexible definition of the `ExplosionSource` parameters: in addition to `volume` we should consider `tons_tnt` or enable to give the magnitude in `tsar`. :grin:

**Comment by hvasbath** [comment]
included as SourceWithDerivedMagnitude ...

**Pull request closed without merging**
