### PR TITLE
fix source.keys() to return correct attribute names

### PR DESCRIPTION
**Pull request by hvasbath**

### CODE REVIEW

**Comment by emolch** [comment]
It should also work if we replace `_keys` with `__keys`. (Then Python should name-mangle the `__keys` to something like `__<classname>_keys` and every subclass will have an independent list of keys).

**Comment by hvasbath** [comment]
Did try it but doesnt change anything. Why should the additional "_" change something? Its just a name isnt it? Nevermind I will commit it and you can see ... Maybe I misunderstood.

**Comment by emolch** [comment]
It's described e.g. here:

https://docs.python.org/2/tutorial/classes.html#private-variables-and-class-local-references

**Comment by emolch** [comment]
I will look at it later...

**Comment by hvasbath** [comment]
Fixed on the python3-testing branch ...

**Pull request closed without merging**
