### PR TITLE
Marker with uncertainty

### PR DESCRIPTION
**Pull request by HerrMuellerluedenscheid**
- Press shift and scroll to set uncertainty of PhaseMarkers. Testing read and write of old and new (with/without uncertainty) formatted marker files.
- Press arrows up/down to set polarity of PhaseMarkers

example

### CODE REVIEW

**Comment by grajh** [comment]
Looks great! Can't wait to try it. :)

Kartoffelbrei, lol.

**Comment by grajh** [comment]
Hello!

Any news on the progress of this feature?

**Comment by HerrMuellerluedenscheid** [comment]
Hey,

not really. Sorry for the delay! I started to extend this feature to be available also for other marker types but haven't finished, yet. I'll try to finish it before Christmas. However, you can already use it by checkout out this branch and installing pyrocko from there.

**Comment by grajh** [comment]
Hi!

Thanks for the update. Don't worry, just wanted to know what is going on. I really appreciate the work of your group.

**Comment by grajh** [comment]
Hi!

I cloned the marker_with_uncertainty branch and did a fresh install on Ubuntu 17.10 with:

```
sudo apt-get install -y make git python3-dev python3-setuptools
sudo apt-get install -y python3-numpy python3-numpy-dev python3-scipy python3-matplotlib
sudo apt-get install -y python3-pyqt4 python3-pyqt4.qtopengl
sudo apt-get install -y python3-pyqt5 python3-pyqt5.qtopengl python3-pyqt5.qtsvg
sudo apt-get install -y python3-pyqt5.qtwebengine || sudo apt-get install -y python3-pyqt5.qtwebkit
sudo apt-get install -y python3-yaml python3-progressbar python3-jinja2
sudo apt-get install -y python3-requests
sudo apt-get install -y python3-future || sudo easy_install3 future
cd ~/python_source
git clone -b marker_with_uncertainty https://github.com/pyrocko/pyrocko.git
cd pyrocko
sudo python3 setup.py install
```

I got no errors during install. However, when I run snuffler I get an error.

```
Traceback (most recent call last):
  File "/usr/local/bin/snuffler", line 11, in <module>
    load_entry_point('pyrocko==2017.11', 'gui_scripts', 'snuffler')()
  File "/usr/local/lib/python3.6/dist-packages/pyrocko/apps/snuffler.py", line 10, in main
    snuffler.snuffler_from_commandline(args=args)
  File "/usr/local/lib/python3.6/dist-packages/pyrocko/gui/snuffler.py", line 320, in snuffler_from_commandline
    store_interval=options.store_interval)
  File "/usr/local/lib/python3.6/dist-packages/pyrocko/gui/snuffler.py", line 87, in snuffle
    win = SnufflerWindow(pile, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pyrocko/gui/snuffler_app.py", line 439, in __init__
    panel_parent=self)
  File "/usr/local/lib/python3.6/dist-packages/pyrocko/gui/pile_viewer.py", line 3877, in __init__
    panel_parent=panel_parent)
  File "/usr/local/lib/python3.6/dist-packages/pyrocko/gui/pile_viewer.py", line 758, in __init__
    self.config = pyrocko.config.config('snuffler')
  File "/usr/local/lib/python3.6/dist-packages/pyrocko/config.py", line 176, in config
    return processed(raw_config(config_name))
  File "/usr/local/lib/python3.6/dist-packages/pyrocko/config.py", line 164, in raw_config
    g_conf[config_name] = load(filename=conf_path)
  File "/usr/local/lib/python3.6/dist-packages/pyrocko/guts.py", line 116, in g
    retval = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pyrocko/guts.py", line 1620, in load
    return _load(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pyrocko/guts.py", line 1265, in _load
    return yaml.load(stream=stream, Loader=SafeLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 41, in construct_document
    data = self.construct_object(node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 88, in construct_object
    data = constructor(self, tag_suffix, node)
  File "/usr/local/lib/python3.6/dist-packages/pyrocko/guts.py", line 1297, in multi_constructor
    o = cls(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pyrocko/guts.py", line 662, in __init__
    self.T.tagname, ', '.join(list(kwargs.keys()))))
pyrocko.guts.ArgumentError: Invalid argument to pf.SnufflerConfig: first_start
```

Any idea?

**Comment by emolch** [comment]
The config entry `first_start` in `~/.pyrocko/snuffler.pf` has been introduced after `marker_with_uncertainty` has been branched off `master`. Just remove this line from the config file and it should work fine again. Maybe someone (@HerrMuellerluedenscheid?) can rebase the branch to current master, this would also solve the problem.

**Comment by grajh** [comment]
Oh, it worked. Many thanks.

**Comment by d-chambers** [comment]
Anything I can do to help here? I am very interested in using these features.

**Comment by HerrMuellerluedenscheid** [comment]
I attempted a rebase of this branch which turned out cumbersome. So, instead I cherry-picked and improved the changes and gave it a fresh start based on the current master branch (see #277 ).
Thanks for waiting so patient. If you like, please feel free to checkout #277  and give it a try. I'm happy about every feedback.

**Pull request closed without merging**
